### ISSUE TITLE
urls are encoded in JSON payload

### ISSUE THREAD

**Issue by ginxwar** [StraboSpot/strabo-server#20]
I've noticed that in a few cases, wherever there is a URL in the JSON, it is almost always encoded, but the api documentation does not mention this.

Can we avoid encoded URLs in the JSON payload?

GET http://www.strabospot.org/db/myDatasets

```
{
  "datasets": [
    {
      "name": "kevindataset",
      "datecreated": "June 29, 2015, 10:21 pm MDT -06:00",
      "self": "http:\\/\\/strabospot.org\\/db\\/dataset\\/57133",
      "datasettype": "app"
    }
  ]
}
```

**Comment by jasonash** [comment]
According to www.json.org, the default behaviour is to escape solidus (forward slash) characters in JSON encoded data. PHP’s json_encode function follows this spec, so solidus characters are escaped or “encoded” in the output of the Strabo REST API.

Beginning with PHP 5.4, there exists the option to negate this behaviour, but unfortunately our server is running an old version of Ubuntu which does not allow installation of PHP 5.4 via the standard repos. Of course, there are workarounds to force a newer version of PHP but these would break updates and should probably be performed by a system admin. It is my suggestion that the server be upgraded to 14.04 LTS so that we might keep up with these sorts of PHP enhancements. Until the server is upgraded, there isn’t an easy solution to this problem.

**Comment by jessica-azgs** [comment]
@jasonash Do you need me to do anything in order to upgrade the server, if this is what you're suggesting?

**Comment by jasonash** [comment]
@jessica-azgs Ideally, the server should be updated to Ubuntu 14.04 LTS to take advantage of improvements in PHP. Unfortunately, this is a task for a system admin. While it is possible for me to upgrade the server, I wouldn't feel comfortable doing so as I am not the party responsible for maintaining the machine. When the server was first set up, I recall that there were issues with the AZGS running 14.04, but I don't recall the exact reasoning. Whatever the case, it would be nice to have the latest version of PHP to work with.

**Comment by jessica-azgs** [comment]
@jasonash Did you change something with this in the past few days? I'm now getting an error trying to add a feature to a dataset where I wasn't before. I am getting something like `http://strabospot.org/db/datasetSpots/57226 404 (Not Found)`. If I request all datasets 57226 is there but self is `"self":"http:\/\/strabospot.org\/db\/dataset\/57226"`. This was working fine a few days ago though I don't remember getting the backslashes in the url from the server before.

**Comment by jasonash** [comment]
@jessica-azgs No, I haven't changed any behavior. I just added a spot to a dataset and didn't have any issues. It is working fine. As for the slashes in the URL, that has always been the behavior. Can you be more specific as to what call you are doing to get an error. Do you have a CURL statement that I can test?

**Comment by jessica-azgs** [comment]
@jasonash Ok, moving this last issue to another thread then.
