### ISSUE TITLE
Handle new spot data model server-side

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/strabo-server#28]
Two big changes to the spot data model:
1. Allow multiple orientation measurements for a single Spot
2. Allow one rock unit for a Spot

The orientation fields are pulled from the KoBo forms TabularZoneOrienation, LinearOrienation and Planar Orientation with the EXCEPTION of the fields orientation_type. I have the app adding that in so we know what type of orientation measurement we have. The values for this field are linear_orientation, planar_orientation or tabular_zone_orientation.

You'll also note that each orientation measurement can have an associated orientation. Those measurements are in an array called associated_orientation.

@jasonash If you think this should be structured differently let me know. I am going to start integrating this into the map and after that I will work on the sync functionality.

Here is a capture of what the data model looks like:
![spotobj](https://cloud.githubusercontent.com/assets/1493985/11850238/55b6456c-a3e9-11e5-960b-fdde64850a65.PNG)

And here is what the same spot looks like on the orientation page:
![spotapp](https://cloud.githubusercontent.com/assets/1493985/11850102/970dd10c-a3e8-11e5-871d-14482a708e59.PNG)

**Comment by jessica-azgs** [comment]
@jasonash I just went through the KoBo forms for each of the orientation measurement types and changed the field names. So for example before we had planar_strike and line_strike in their respective forms but now both field names are just strike. Since we're differentiating between the different orientation measurement types with the field orientation_type, as described in the post above, we do not need to differentiate in the other field names. This makes the coding less verbose.

**Comment by jasonash** [comment]
@jessica-azgs I have altered the REST API to handle the new data model. I have attached my test JSON document. Of course, this document isn't comprehensive, but all of the new KoBo form fields should work fine. Please let me know when you are done with the app side, and I will test the server functionality further.
[new_model_json.txt](https://github.com/StraboSpot/strabo-server/files/66845/new_model_json.txt)

**Comment by jessica-azgs** [comment]
@jasonash Did you see my message above, just before your last one, where I changed the field names? Your test json still has the old field names with planar_feature_type instead of feature_type and line_plunge instead of plunge as two examples. All the field names I'm using are in KoBo. If we have the field names correct they should download and show up in the app fine.

**Comment by jasonash** [comment]
@jessica-azgs  Yes, I saw the message. Sorry, I sent my original document. The new names should work fine.

**Comment by jessica-azgs** [comment]
@jasonash Oh ok. Spots created in the app seem to be uploading and downloading fine. Not sure about if someone creates spots from a shapefile through your interface.

(Btw I never changed to the new dev db you set up .. still using http://strabospot.org/db/)

**Comment by jasonash** [comment]
@jessica-azgs The shapefile parser will need some re-work to fit with the new data model. I will work on this next. No, I went ahead and kept the api at db since the app wasn't working with it any longer.
